version: 0.2

phases:
  install:
    commands:
      - echo "Installing ssh client..."
      - yum install -y openssh-clients

  build:
    commands:
      - echo "Writing private key"
      - echo "$PRIVATE_KEY" > lab_project.pem
      - chmod 400 lab_project.pem
      - echo "Checking EC2 IP: $EC2_IP"
      - echo "Pinging EC2..."
      - ping -c 4 $EC2_IP
      - echo "Trying ssh connection"
      - ssh -o StrictHostKeyChecking=no -i lab_project.pem ec2-user@$EC2_IP "echo '✅ SSH CONNECTED'"
      - echo "Using SCP to copy index.html"
      - scp -o StrictHostKeyChecking=no -i lab_project.pem index.html ec2-user@$EC2_IP:/home/ec2-user/

artifacts:
  files:
    - index.html
